### ISSUE TITLE
 Python 3.6.ipynb : not getting the same results as your notebook

### ISSUE THREAD

**Issue by nidhimoore** [t-davidson/hate-speech-and-offensive-language#10]
Hi,
I am running your Python 3.6 notebook( src directory) . Howerver I am getting different results to the ones shown in the notebook.  My 'M' matrix which is input to the model, has (24783,4023) dimensions as opposed to (24783,11172) shown in your notebook.

I have downloaded your code and then installed all the required packages. Code is running fine. DO I need to do something else to get the same results as shown in your notebook?

My Reults:
print(report)
          precision    recall  f1-score   support

           0       0.38      0.46      0.42       164
           1       0.93      0.87      0.90      1905
           2       0.67      0.79      0.73       410

   micro avg       0.83      0.83      0.83      2479
   macro avg       0.66      0.71      0.68      2479
weighted avg       0.85      0.83      0.84      2479

**Comment by t-davidson** [comment]
I suggest you check at each step of the preprocessing to identigy when your M matrix has fewer columns than the one in the example. It is likely that some function in Python has changed and is causing the data to be processed different. I'm afraid I do not have time to help you to debug your code.
