### ISSUE TITLE
Bug in tokenize and basic_tokenize

### ISSUE THREAD

**Issue by soumitra9** [t-davidson/hate-speech-and-offensive-language#14]
Hi, I noticed a bug in the tokenizing functions in the notebooks. In the tokenize function the regex used is

 tweet = " ".join(re.split("[^a-zA-Z]*", tweet.lower())).strip()  --> I think the '*' should be replaced with a '+' as this particular regex renders the tweet as a list of charachters

Same with the basic_teknize function.

**Comment by AdityaYadav29** [comment]
@soumitra9 I faced the same problem and I did the same thing as you have mentioned and it worked.

**Comment by TiagoMAntunes** [comment]
+1

@t-davidson we know you don't maintain this anymore, but it would be nice if you could update it. it's just a small change

`tweet = " ".join(re.split("[^a-zA-Z]*", tweet.lower())).strip()`

should become

`tweet = " ".join(re.split("[^a-zA-Z]+", tweet.lower())).strip()`

**Comment by t-davidson** [comment]
Thank you for identifying the issue. I am not actively maintaining this repository, but I will update the README to encourage users to read the closed issues.
