### ISSUE TITLE
Research Paper Link Not Working

### ISSUE THREAD

**Issue by AyeshaIrshad1337** [t-davidson/hate-speech-and-offensive-language#16]
This following link has no research paper can you share the correct link : https://aaai.org/ocs/ICWSM/ICWSM17/paper/view/15665

**Comment by ingmarweber** [comment]
Thanks for flagging this.
The updated link is: https://ojs.aaai.org/index.php/ICWSM/article/view/14955

Ingmar (one of the co-authors)
