### ISSUE TITLE
LSA

### ISSUE THREAD

**Issue by eloiup** [t-davidson/hate-speech-and-offensive-language#2]
since you are alrdy doing tfidf, why not do lsa as well?

**Comment by t-davidson** [comment]
Good question. When we wrote the paper we were focusing on easily interpreting different features, so having particular tokens makes more sense than having components in a truncated SVD, although I know the latter can also be interpreted. I recently coauthored a tutorial where we also do LSA using these data, and find that it does lead to small improvements in model performance, although it seem to make too much difference: xrds.acm.org/article.cfm?aid=3155212 (its paywalled, but I'll send you a copy if you email me).
