### ISSUE TITLE
errors provided from initial code

### ISSUE THREAD

**Issue by terry07** [t-davidson/hate-speech-and-offensive-language#4]
I am getting error on the two following points:

from textstat.textstat import *

and the message when i am importing this module is the following: "module repoze.lru is missing"

**Comment by jonzarecki** [comment]
I've run into the same problem and I think you can use my pending pull request to fix it. Same for #3

**Comment by t-davidson** [comment]
I do not have the same issue so it must be due to incompatibility with a new version of textstat. I have merged the PR so let me know if it is fixed.

**Comment by terry07** [comment]
Dear t-davidson,

thanks for your help. It is all fixed now.
