### ISSUE TITLE
Error while loading TF-IDFVectorizer

### ISSUE THREAD

**Issue by shraghuna** [t-davidson/hate-speech-and-offensive-language#6]
I'm trying to run the classifier on custom data, and I get this error:

<i>Traceback (most recent call last):
  File "classifier.py", line 43, in <module>
    tf_vectorizer = joblib.load('final_tfidf.pkl')
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1132, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'tokenize'</i>

I'm using python2 and scikit-learn 0.19.1.

Do I need a particular version of scikit-learn to un-pickle the files provided in the repo? If not, any suggestions are welcome and appreciated.

**Comment by t-davidson** [comment]
I think you need to download the correct modules for NLTK after installking it, see https://stackoverflow.com/questions/37101114/what-to-download-in-order-to-make-nltk-tokenize-word-tokenize-work?rq=1

**Comment by shraghuna** [comment]
I have already downloaded the correct modules for NLTK, but I'm still facing the same issue.
Unpickling is probably am issue here because of version conflicts. Do you have any other thoughts about the same?

**Comment by t-davidson** [comment]
It should be relatively simple to run one of the notebooks to retrain the classifier instead of using the pickled version.
