### ISSUE TITLE
Invalid keyword 'encoding' in open

### ISSUE THREAD

**Issue by karinseve** [t-davidson/hate-speech-and-offensive-language#7]
Hi, I'm trying to train a classifier with your method. I've cloned your repository, created a virtualenv, and installed all the packages required to run your classifier. 
The results of my `pip freeze` is this: 
```
certifi==2018.4.16
chardet==3.0.4
idna==2.6
nltk==3.3
numpy==1.14.3
pandas==0.23.0
Pyphen==0.9.4
python-dateutil==2.7.3
pytz==2018.4
repoze.lru==0.7
requests==2.18.4
scikit-learn==0.19.1
scipy==1.1.0
six==1.11.0
sklearn==0.0
textstat==0.4.1
urllib3==1.22
vaderSentiment==3.2.1

```

I have then run the classifier with the command you provided on the README `python classifier.py`, but the output is:
```
Traceback (most recent call last):
  File "classifier.py", line 36, in <module>
    sentiment_analyzer = VS()
  File "/.../vaderSentiment/vaderSentiment.py", line 212, in __init__
    with open(lexicon_full_filepath, encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

Would it be also possible for you to share a list of requirements (https://pip.readthedocs.io/en/1.1/requirements.html)?

Thank you

**Comment by deepkshikha** [comment]
It's a version error. It will work well in python 3.6

**Comment by t-davidson** [comment]
Please run the code using 3.6 and you should have no problems.

**Comment by vishrutkohli** [comment]
but all the pickle files are saved under protocol 2 so it is not working with Python 3.6
