### ISSUE TITLE
Imbalanced dat

### ISSUE THREAD

**Issue by deepkshikha** [t-davidson/hate-speech-and-offensive-language#8]
I have used your data set. I am using keras and trained using lstm I am getting poor result for 2 classes how have you over come that

**Comment by t-davidson** [comment]
I haven't used Keras on this dataset so I'm not sure how you would go about it using that package. In sklearn the 'class_weight' parameter is important to consider, as you can use it to compensate for class imbalance (https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/class_weight.py). You should be able to implement something similar in Keras. You may also want to consider using the [imbalanced learn](https://github.com/scikit-learn-contrib/imbalanced-learn) module to deal with imbalance. 

If you are concerned about improving upon the results in the original paper I suggest reading some of the studies that have cited ours (you can find them on Google Scholar) as some authors have used neural networks and improved upon our performance.

Overall just remember that this is a hard prediction problem and the classes are difficult to separate (particularly hate and offensive) so it will be difficult to get very high predictive performance.

**Comment by deepkshikha** [comment]
@t-davidson thanks although I have tried LSTM, CNN but not getting better result for first class.
