### ISSUE TITLE
Possible to provide Tweet IDs in the data?

### ISSUE THREAD

**Issue by MWYang** [t-davidson/hate-speech-and-offensive-language#9]
The original dataset on [data.world](https://data.world/crowdflower/hate-speech-identification) contains the ID number for each tweet. Would it be possible to update this repo to include that information as well?

In my early-stage research, I would like to use the tweet ID for two things:

- Checking whether the tweet has been deleted or removed (potentially for violating community policies)
- Doing user research on the original tweeter (to try and extract features like gender and political orientation from their other tweets)

Thanks!

**Comment by t-davidson** [comment]
@MWYang thanks for your question. The version of the dataset you refer to was shared without our permission so we have no control over it. The canonical version of the data is the one located here. We did not originally share tweet IDs but are planning on doing so in the future, but I am unable to share them now. If you are interested in similar datasets with tweet IDs you might conside this repository by Zeerak Waseem: https://github.com/ZeerakW/hatespeech. Having done some analysis of this data myself I can tell you that the hateful tweets seem more likely to be deleted or removed.
